# Generated by Django 4.0.5 on 2022-07-26 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('calories_unit', models.DecimalField(decimal_places=3, max_digits=6)),
                ('protein_unit', models.DecimalField(decimal_places=3, max_digits=6)),
                ('carbs_unit', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_fat_unit', models.DecimalField(decimal_places=3, max_digits=6)),
                ('sat_fat_unit', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fiber_unit', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'db_table': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cdate', models.DateField(db_column='date')),
                ('food', models.ForeignKey(db_column='food', on_delete=django.db.models.deletion.CASCADE, to='FoodJournal.foods')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Meals',
            },
        ),
        migrations.AddField(
            model_name='foods',
            name='measurement_unit',
            field=models.ForeignKey(db_column='measurement_unit', on_delete=django.db.models.deletion.CASCADE, to='FoodJournal.measurements'),
        ),
    ]
